package lk.ijse.gdse71.backend.entity;

public enum ServiceType {
    SHIP_AGENCY_OR_HUSBANDRY_SERVICES,
    PROVISION_SUPPLY,
    CREW_SERVICE,
    SUPPLY_OF_SHIP_SERVICE,
    CLEARING_AND_FORWARDING_SHIP_SPARES,
    UNDERWATER_SERVICE,
    CARGO_TANK_CLEANING,
    MARINE_LUBRICANTS,
    BUNKER_BROKERING,
    OTHER_SERVICE
}
